/*
  Generator:

  let match, msg = "<img src=\"\/assets\/faces\/fs\/smile.gif\" class=\"hkgmoji\" \/>"
  msg = msg.replace(/<img(.*?)src="(.*?)"(.*?)>/gi, '[img]$2[/img]')
  const iconsRegex = /\[img\].*?assets\/faces(.*?)\[\/img\]/
  while (match = iconsRegex.exec(msg)) {
    const url = match[1]
    msg = msg.replace(iconsRegex, url)
  }
  let vals = '#:)#fs'
  vals = vals.split(' ')
  const result = JSON.stringify(msg.split(' ').reduce((prev, curr, i) => {
    return Object.assign(prev, {
      [curr]: vals[i]
    })
  }, {})).replace(/"/g, '\'').replace(/:'/g, ': \'').replace(/,/g, ',\n  ')
  console.log(result)
*/

const normal = {
  '/normal/smile.gif': ':)',
  '/normal/angel.gif': 'O:-)',
  '/normal/dead.gif': 'xx(',
  '/normal/clown.gif': ':o)',
  '/normal/frown.gif': ':-(',
  '/normal/cry.gif': ':~(',
  '/normal/wink.gif': ';-)',
  '/normal/angry.gif': ':-[',
  '/normal/devil.gif': ':-]',
  '/normal/biggrin.gif': ':D',
  '/normal/oh.gif': ':O',
  '/normal/tongue.gif': ':P',
  '/normal/kiss.gif': '^3^',
  '/normal/wonder.gif': '?_?',
  '/normal/agree.gif': '#yup#',
  '/normal/donno.gif': '#ng#',
  '/normal/hehe.gif': '#hehe#',
  '/normal/love.gif': '#love#',
  '/normal/surprise.gif': '#oh#',
  '/normal/chicken.gif': '#cn#',
  '/normal/ass.gif': '#ass#',
  '/normal/sosad.gif': '[sosad]',
  '/normal/good.gif': '#good#',
  '/normal/hoho.gif': '#hoho#',
  '/normal/kill.gif': '#kill#',
  '/normal/bye.gif': '#bye#',
  '/normal/z.gif': 'Z_Z',
  '/normal/@.gif': '@_@',
  '/normal/adore.gif': '#adore#',
  '/normal/wonder2.gif': '#???#',
  '/normal/banghead.gif': '[banghead]',
  '/normal/bouncer.gif': '[bouncer]',
  '/normal/bouncy.gif': '[bouncy]',
  '/normal/offtopic.gif': '[offtopic]',
  '/normal/censored.gif': '[censored]',
  '/normal/flowerface.gif': '[flowerface]',
  '/normal/shocking.gif': '[shocking]',
  '/normal/photo.gif': '[photo]',
  '/normal/fire.gif': '#fire#',
  '/normal/yipes.gif': '[yipes]',
  '/normal/369.gif': '[369]',
  '/normal/bomb.gif': '[bomb]',
  '/normal/slick.gif': '[slick]',
  '/normal/fuck.gif': '#fuck#',
  '/normal/no.gif': '#no#',
  '/normal/kill2.gif': '#kill2#',
  '/normal/dislike.gif': '#dislike#',
  '/normal/like.gif': '#like#',
}

const big = {
  '/big/smile.gif': '#:)#b',
  '/big/angel.gif': '#O:-)#b',
  '/big/dead.gif': '#xx(#b',
  '/big/clown.gif': '#:o)#b',
  '/big/frown.gif': '#:-(#b',
  '/big/cry.gif': '#:~(#b',
  '/big/wink.gif': '#;-)#b',
  '/big/angry.gif': '#:-[#b',
  '/big/devil.gif': '#:-]#b',
  '/big/biggrin.gif': '#:D#b',
  '/big/oh.gif': '#:O#b',
  '/big/tongue.gif': '#:P#b',
  '/big/kiss.gif': '#^3^#b',
  '/big/wonder.gif': '#?_?#b',
  '/big/agree.gif': '#yup#b',
  '/big/donno.gif': '#ng#b',
  '/big/hehe.gif': '#hehe#b',
  '/big/love.gif': '#love#b',
  '/big/surprise.gif': '#oh#b',
  '/big/chicken.gif': '#cn#b',
  '/big/ass.gif': '#ass#b',
  '/big/sosad.gif': '#[sosad]#b',
  '/big/good.gif': '#good#b',
  '/big/hoho.gif': '#hoho#b',
  '/big/kill.gif': '#kill#b',
  '/big/bye.gif': '#bye#b',
  '/big/z.gif': '#Z_Z#b',
  '/big/@.gif': '#@_@#b',
  '/big/adore.gif': '#adore#b',
  '/big/wonder2.gif': '#???#b',
  '/big/banghead.gif': '#[banghead]#b',
  '/big/bouncer.gif': '#[bouncer]#b',
  '/big/bouncy.gif': '#[bouncy]#b',
  '/big/offtopic.gif': '#[offtopic]#b',
  '/big/censored.gif': '#[censored]#b',
  '/big/flowerface.gif': '#[flowerface]#b',
  '/big/shocking.gif': '#[shocking]#b',
  '/big/photo.gif': '#[photo]#b',
  '/big/fire.gif': '#fire#b',
  '/big/yipes.gif': '#[yipes]#b',
  '/big/369.gif': '#[369]#b',
  '/big/bomb.gif': '#[bomb]#b',
  '/big/slick.gif': '#[slick]#b',
  '/big/fuck.gif': '#fuck#b',
  '/big/no.gif': '#no#b',
  '/big/kill2.gif': '#kill2#b',
  '/big/like.gif': '#like#b',
  '/big/dislike.gif': '#dislike#b',
  '/big/lomore_agree.gif': '#yup#lm#b',
  '/big/lomore_bouncer.gif': '#bouncer#lm#b',
  '/big/lomore_bye.gif': '#bye#lm#b',
  '/big/lomore_shocking.gif': '#shocking#lm#b',
}

const sad = {
  '/fs/smile.gif': '#:)#fs',
  '/fs/angel.gif': '#O:-)#fs',
  '/fs/dead.gif': '#xx(#fs',
  '/fs/clown.gif': '#:o)#fs',
  '/fs/wink.gif': '#;-)#fs',
  '/fs/angry.gif': '#:-[#fs',
  '/fs/devil.gif': '#:-]#fs',
  '/fs/biggrin.gif': '#:D#fs',
  '/fs/oh.gif': '#:O#fs',
  '/fs/tongue.gif': '#:P#fs',
  '/fs/kiss.gif': '#^3^#fs',
  '/fs/wonder.gif': '#?_?#fs',
  '/fs/agree.gif': '#yup#fs',
  '/fs/love.gif': '#love#fs',
  '/fs/chicken.gif': '#cn#fs',
  '/fs/sosad.gif': '#[sosad]#fs',
  '/fs/good.gif': '#good#fs',
  '/fs/hoho.gif': '#hoho#fs',
  '/fs/kill.gif': '#kill#fs',
  '/fs/bye.gif': '#bye#fs',
  '/fs/adore.gif': '#adore#fs',
  '/fs/wonder2.gif': '#???#fs',
  '/fs/bouncer.gif': '#[bouncer]#fs',
  '/fs/bouncy.gif': '#[bouncy]#fs',
  '/fs/offtopic.gif': '#[offtopic]#fs',
  '/fs/censored.gif': '#[censored]#fs',
  '/fs/flowerface.gif': '#[flowerface]#fs',
  '/fs/shocking.gif': '#[shocking]#fs',
  '/fs/369.gif': '#[369]#fs',
  '/fs/bomb.gif': '#[bomb]#fs',
  '/fs/fuck.gif': '#fuck#fs',
  '/fs/no.gif': '#no#fs',
  '/fs/kill2.gif': '#kill2#fs',
  '/fs/battle.gif': '#battle#fs',
  '/fs/south_bear.gif': '#bear#fs',
  '/fs/want_die.gif': '#die#fs',
  '/fs/fozen_smile.gif': '#:)#ice#fs',
  '/fs/green_cap.gif': '#gcap#fs',
  '/fs/green_cap_2.gif': '#gcap2#fs',
  '/fs/green_cap_3.gif': '#gcap3#fs',
  '/fs/jj.gif': '#jj#fs',
  '/fs/lomore_hoho.gif': '#hoho#lm#fs',
  '/fs/lomore_kill.gif': '#kill#lm#fs',
  '/fs/lomore_smile.gif': '#:)#lm#fs',
  '/fs/poison.gif': '#poison#fs',
  '/fs/pokemon_1.gif': '#poke1#fs',
  '/fs/pokemon_2.gif': '#poke2#fs',
  '/fs/smile_big.gif': '#:)#b#fs',
  '/fs/superman.gif': '#superman#fs',
}

export default {
  ...normal,
  ...big,
  ...sad,
}
